#!/bin/sh
set -u

log() { echo "[$(date +'%H:%M:%S')] $*"; }

MIHOMO_DIR=/etc/mihomo
APP_DIR="$MIHOMO_DIR/remnasub"
PROFILE="$APP_DIR/profile.conf"
SOURCE="$APP_DIR/source.yaml"
META="$APP_DIR/source.meta"
ERROR_FILE="$APP_DIR/last-error.txt"
RUNTIME_DIR=/dev/shm/remnasub
FINAL="$RUNTIME_DIR/config.yaml"
WEB_ROOT=/www
WEBROOT=/dev/shm/web
HTTPD_CONF=/etc/httpd.conf

BASIC_AUTH_HASH_DEFAULT='$1$mihomors$BipEGg3TOdgaQSFfGtisO1'
BASIC_AUTH="${BASIC_AUTH:-on}"
BASIC_AUTH_USER="${BASIC_AUTH_USER:-admin}"
BASIC_AUTH_HASH="${BASIC_AUTH_HASH:-$BASIC_AUTH_HASH_DEFAULT}"

mkdir -p "$APP_DIR" "$RUNTIME_DIR"

seed_profile() {
  [ -f "$PROFILE" ] && return 0
  cat > "$PROFILE" <<'EOF'
PROFILE_VERSION=1
SUB_URL_B64=
SUB_HEADERS_B64=
SUB_REFRESH_SECONDS=3600
SUB_TIMEOUT_SECONDS=30
SUB_INSECURE_TLS=0
MIXED_ENABLED=1
MIXED_NAME=mixed-in
MIXED_PORT=7890
MIXED_LISTEN=0.0.0.0
MIXED_UDP=1
MIXED_USERS_B64=
EOF
  chmod 600 "$PROFILE" 2>/dev/null || true
}

seed_profile

setup_auth() {
  : > "$HTTPD_CONF" || return 1
  chmod 600 "$HTTPD_CONF" 2>/dev/null || true
  if [ "$BASIC_AUTH" != "off" ]; then
    printf '/:%s:%s\n' "$BASIC_AUTH_USER" "$BASIC_AUTH_HASH" >> "$HTTPD_CONF"
    log "web basic auth enabled for '$BASIC_AUTH_USER'"
  else
    log "WARNING: web basic auth is disabled"
  fi
}

build_webroot() {
  mount -o remount,exec /dev/shm 2>/dev/null || true
  rm -rf "$WEBROOT"
  mkdir -p "$WEBROOT/cgi-bin" "$WEBROOT/assets"
  for file in _remna.sh remna-profile remna-status remna-config remna-refresh; do
    cp "$WEB_ROOT/cgi-bin/$file" "$WEBROOT/cgi-bin/$file"
  done
  chmod 0644 "$WEBROOT/cgi-bin/_remna.sh" 2>/dev/null || true
  chmod 0755 "$WEBROOT/cgi-bin/remna-profile" "$WEBROOT/cgi-bin/remna-status" "$WEBROOT/cgi-bin/remna-config" "$WEBROOT/cgi-bin/remna-refresh" 2>/dev/null || true
  cp "$WEB_ROOT/index.html" "$WEBROOT/index.html"
  cp "$WEB_ROOT/assets/remna.css" "$WEBROOT/assets/remna.css"
  cp "$WEB_ROOT/assets/remna.js" "$WEBROOT/assets/remna.js"
}

b64_decode_file() {
  value="$1"
  [ -n "$value" ] || return 0
  printf '%s' "$value" | openssl base64 -d -A 2>/dev/null
}

load_profile() {
  SUB_URL_B64= SUB_HEADERS_B64= MIXED_USERS_B64=
  SUB_REFRESH_SECONDS=3600 SUB_TIMEOUT_SECONDS=30 SUB_INSECURE_TLS=0
  MIXED_ENABLED=1 MIXED_NAME=mixed-in MIXED_PORT=7890 MIXED_LISTEN=0.0.0.0 MIXED_UDP=1
  # profile.conf is generated by our CGI and contains only KEY=VALUE lines.
  while IFS='=' read -r key value; do
    case "$key" in
      SUB_URL_B64|SUB_HEADERS_B64|SUB_REFRESH_SECONDS|SUB_TIMEOUT_SECONDS|SUB_INSECURE_TLS|MIXED_ENABLED|MIXED_NAME|MIXED_PORT|MIXED_LISTEN|MIXED_UDP|MIXED_USERS_B64)
        eval "$key=\$value"
        ;;
    esac
  done < "$PROFILE"
}

valid_number() { case "$1" in ''|*[!0-9]*) return 1 ;; *) return 0 ;; esac; }

fetch_source() {
  load_profile
  url="$(b64_decode_file "$SUB_URL_B64")"
  [ -n "$url" ] || {
    rm -f "$FINAL"
    printf '%s\n' "Subscription URL is not configured" > "$ERROR_FILE"
    return 1
  }
  case "$url" in http://*|https://*) ;; *) printf '%s\n' "Subscription URL must use http(s)" > "$ERROR_FILE"; return 1 ;; esac
  valid_number "$SUB_TIMEOUT_SECONDS" || SUB_TIMEOUT_SECONDS=30
  [ "$SUB_TIMEOUT_SECONDS" -ge 3 ] && [ "$SUB_TIMEOUT_SECONDS" -le 120 ] || SUB_TIMEOUT_SECONDS=30
  tmp="$SOURCE.tmp.$$"
  set -- -q -T "$SUB_TIMEOUT_SECONDS" -O "$tmp" --user-agent="Mihomo-RemnaSub-RoS/1"
  headers="$(b64_decode_file "$SUB_HEADERS_B64")"
  if [ -n "$headers" ]; then
    while IFS= read -r header; do
      [ -n "$header" ] && set -- "$@" --header="$header"
    done <<EOF
$headers
EOF
  fi
  [ "$SUB_INSECURE_TLS" = 1 ] && set -- "$@" --no-check-certificate
  if ! wget "$@" "$url"; then
    rm -f "$tmp"
    printf '%s\n' "Subscription download failed" > "$ERROR_FILE"
    return 1
  fi
  [ -s "$tmp" ] || { rm -f "$tmp"; printf '%s\n' "Subscription response is empty" > "$ERROR_FILE"; return 1; }
  [ "$(wc -c < "$tmp")" -le 16777216 ] || { rm -f "$tmp"; printf '%s\n' "Subscription exceeds 16 MiB" > "$ERROR_FILE"; return 1; }
  if ! mihomo -t -d "$MIHOMO_DIR" -f "$tmp" >/dev/null 2>&1; then
    mv "$tmp" "$APP_DIR/invalid-source.yaml" 2>/dev/null || rm -f "$tmp"
    printf '%s\n' "Downloaded YAML is rejected by mihomo" > "$ERROR_FILE"
    return 1
  fi
  mv "$tmp" "$SOURCE"
  printf 'fetched_at=%s\nfetched_epoch=%s\nbytes=%s\n' "$(date -Iseconds)" "$(date +%s)" "$(wc -c < "$SOURCE")" > "$META"
  rm -f "$ERROR_FILE"
  return 0
}

write_listeners_overlay() {
  load_profile
  [ "$MIXED_ENABLED" = 1 ] || return 0
  valid_number "$MIXED_PORT" || return 1
  [ "$MIXED_PORT" -ge 1 ] && [ "$MIXED_PORT" -le 65535 ] || return 1
  cat <<EOF
listeners:
  - name: $MIXED_NAME
    type: mixed
    port: $MIXED_PORT
    listen: $MIXED_LISTEN
    udp: $([ "$MIXED_UDP" = 1 ] && echo true || echo false)
EOF
  users="$(b64_decode_file "$MIXED_USERS_B64")"
  if [ -n "$users" ]; then
    echo "    users:"
    while IFS= read -r row; do
      username=${row%%#*}
      password=${row#*#}
      [ "$username" = "$row" ] && continue
      [ -n "$username" ] && [ -n "$password" ] || continue
      printf '      - username: "%s"\n        password: "%s"\n' "$(printf '%s' "$username" | sed 's/[\\"]/\\&/g')" "$(printf '%s' "$password" | sed 's/[\\"]/\\&/g')"
    done <<EOF
$users
EOF
  fi
}

replace_top_level_block() {
  input="$1" output="$2" key="$3" replacement="$4"
  awk -v key="$key" '
    function is_top(line) { return line ~ /^[^[:space:]#][^:]*:/ }
    $0 ~ "^" key ":[[:space:]]*" { skip=1; next }
    skip && is_top($0) { skip=0 }
    !skip { print }
  ' "$input" > "$output"
  if [ -s "$replacement" ]; then
    printf '\n' >> "$output"
    cat "$replacement" >> "$output"
  fi
}

build_final_config() {
  [ -s "$SOURCE" ] || { printf '%s\n' "No valid downloaded subscription" > "$ERROR_FILE"; return 1; }
  overlay="$RUNTIME_DIR/listeners.yaml"
  : > "$overlay"
  if ! write_listeners_overlay > "$overlay"; then
    printf '%s\n' "Listener settings are invalid" > "$ERROR_FILE"
    return 1
  fi
  replace_top_level_block "$SOURCE" "$FINAL.tmp" listeners "$overlay"
  mv "$FINAL.tmp" "$FINAL"
  if ! mihomo -t -d "$MIHOMO_DIR" -f "$FINAL" > "$RUNTIME_DIR/validate.log" 2>&1; then
    printf '%s\n' "Final YAML is rejected by mihomo" > "$ERROR_FILE"
    return 1
  fi
  rm -f "$ERROR_FILE"
  return 0
}

MIHOMO_PID=
RELOAD=1
STOPPING=0

reload() {
  RELOAD=1
  [ -n "$MIHOMO_PID" ] && kill -TERM "$MIHOMO_PID" 2>/dev/null || true
}

stop() {
  STOPPING=1
  [ -n "$MIHOMO_PID" ] && kill -KILL "$MIHOMO_PID" 2>/dev/null || true
  exit 0
}

trap reload USR1 HUP
trap stop TERM INT

supervisor() {
  last_fetch=0
  while [ "$STOPPING" = 0 ]; do
    load_profile
    valid_number "$SUB_REFRESH_SECONDS" || SUB_REFRESH_SECONDS=3600
    [ "$SUB_REFRESH_SECONDS" -ge 30 ] && [ "$SUB_REFRESH_SECONDS" -le 86400 ] || SUB_REFRESH_SECONDS=3600
    url="$(b64_decode_file "$SUB_URL_B64")"
    if [ -z "$url" ]; then
      printf '%s\n' "Subscription URL is not configured" > "$ERROR_FILE"
      rm -f "$FINAL"
      sleep 5
      continue
    fi
    now=$(date +%s)
    if [ "$RELOAD" = 1 ] || [ ! -s "$SOURCE" ] || [ $((now - last_fetch)) -ge "$SUB_REFRESH_SECONDS" ]; then
      RELOAD=0
      if fetch_source && build_final_config; then
        last_fetch=$(date +%s)
        log "subscription refreshed; final config is valid"
      else
        log "subscription refresh failed: $(cat "$ERROR_FILE" 2>/dev/null || echo unknown)"
      fi
    fi
    if [ -s "$FINAL" ]; then
      log "starting mihomo ($(mihomo -v 2>/dev/null | head -n1))"
      mihomo -d "$MIHOMO_DIR" -f "$FINAL" &
      MIHOMO_PID=$!
      wait "$MIHOMO_PID"
      rc=$?
      MIHOMO_PID=
      [ "$STOPPING" = 1 ] && break
      [ "$RELOAD" = 1 ] && continue
      log "mihomo exited ($rc), retrying in 5s"
      sleep 5
    else
      sleep 5
    fi
  done
}

refresh_timer() {
  last_signal=0
  while :; do
    sleep 5
    load_profile
    url="$(b64_decode_file "$SUB_URL_B64")"
    [ -n "$url" ] || continue
    valid_number "$SUB_REFRESH_SECONDS" || SUB_REFRESH_SECONDS=3600
    [ "$SUB_REFRESH_SECONDS" -ge 30 ] && [ "$SUB_REFRESH_SECONDS" -le 86400 ] || SUB_REFRESH_SECONDS=3600
    fetched_epoch=$(awk -F= '$1 == "fetched_epoch" { print $2; exit }' "$META" 2>/dev/null || true)
    valid_number "$fetched_epoch" || continue
    now=$(date +%s)
    [ $((now - fetched_epoch)) -ge "$SUB_REFRESH_SECONDS" ] || continue
    [ $((now - last_signal)) -ge "$SUB_REFRESH_SECONDS" ] || continue
    last_signal=$now
    kill -USR1 1 2>/dev/null || true
  done
}

setup_auth
build_webroot
httpd -f -p 80 -h "$WEBROOT" -c "$HTTPD_CONF" &
log "web UI started on :80"
refresh_timer &
supervisor
